# Generated by Django 3.1.3 on 2020-11-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='wordh',
        ),
    ]
